"""
Django settings for Travencia project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4ann8of@vtp5r*q0thh-=ht=%_jhl$fv(p8l*nl&g&#n11+i91'





#the below SECRET_KEY for honest exports
#SECRET_KEY = 'bs-w5h+-2xpn@q_h4stb$=o@dqjusv@-0^h2wnqm4f)!82%6lu'




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'registration', #should be immediately above 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
   
    'Main.apps.MainConfig',
    'django_activeurl',
    'lazysignup',
    'django_countries',
    'crispy_forms',
    'tinymce',
    'stripe',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    'jquery',
    'post_office',
    'easy_pdf',
    'django.contrib.humanize',
    


]




'''
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.facebook',

'''

ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.
REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.


#Stripe Creds

STRIPE_PUBLIC_KEY= 'pk_test_HcVPnpjRtHQqPVCct3HkhFua00ijCNVC2x'
STRIPE_SECRET_KEY = 'sk_test_azR11t8KYeo5sj4LiIK0HKE200lV6Gnn4H'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


AUTHENTICATION_BACKENDS = (
  'django.contrib.auth.backends.ModelBackend',
  'lazysignup.backends.LazySignupBackend',
)





ROOT_URLCONF = 'Travencia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]


'''


EMAIL_BACKEND = 'post_office.EmailBackend'
POST_OFFICE = {
    'TEMPLATE_ENGINE': 'post_office',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
    {
        'BACKEND': 'post_office.template.backends.post_office.PostOfficeTemplates',
        'APP_DIRS': True,
        'DIRS': [],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
            ]
        }
    }
]


'''



WSGI_APPLICATION = 'Travencia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'travencia',
        'USER':'postgres',
        'PASSWORD':'Ms975899//',
        'HOST':'localhost',
        'PORT':'5432',
    }
}



'''

'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DB_name',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'DB_user',
        'PASSWORD': 'DB_password',
    }
}
'''


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CRISPY_TEMPLATE_PACK = 'bootstrap4'


'''
these are the settings for sagepay

SAGEPAY_VENDOR = 'YOUR_VENDOR_NAME'
SAGEPAY_PASSWORD = 'YOUR_PASSWORD'
SAGEPAY_CURRENCY = 'GBP'
SAGEPAY_VPS_PROTOCOL = '2.23'
# Options are Live, Test and Simulator
SAGEPAY_MODE = 'Simulator
'''


WKHTMLTOPDF_CMD_OPTIONS = {
    'quiet': True,
}


BOOTSTRAP4 = {
    'include_jquery': True,
}
'''
#Django Registration redux settings.
REGISTRATION_OPEN = True
ACCOUNT_ACTIVATION_DAYS = 7
LOGIN_URL = '/accounts/login/'
REGISTRATION_AUTO_LOGIN = True
LOGIN_REDIRECT_URL = '/Authorize/'

EMAIL_BACKEND = 'django_mail_admin.backends.CustomEmailBackend'
'''





#MailChimp Creds

MAILCHIMP_API_KEY = 'fe3c44091d53804b1f8c4e8fdf277512-us19'
MAILCHIMP_DATA_CENTER = 'us19'
MAILCHIMP_EMAIL_LIST_ID = '49e218ab6f'




TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 720,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    }
'''
EMAIL_BACKEND = 'post_office.EmailBackend'
POST_OFFICE = {
    'TEMPLATE_ENGINE': 'post_office',
}
'''




ACTIVE_URL_KWARGS = {
    'css_class': 'Moha',
    'parent_tag': 'li',
    'menu': 'yes',
    'ignore_params': 'no'
}



EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'mojaba808@gmail.com'
EMAIL_HOST_PASSWORD = 'fmqwnycotgmtsdet'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'






'''
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'reservations@travencia.com'
EMAIL_HOST_PASSWORD = 'Vargdark2030$#@'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
'''




SITE_ID = 1
REGISTRATION_DEFAULT_FROM_EMAIL =  ''
REGISTRATION_AUTO_LOGIN = True
ACCOUNT_AUTHENTICATED_REGISTRATION_REDIRECTS = True
LOGIN_REDIRECT_URL = '/'
#    ACCOUNT_EMAIL_REQUIRED = True
#    ACCOUNT_EMAIL_VERIFICATION = "mandatory"
