# Generated by Django 2.2.15 on 2021-03-16 17:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='Burba', editable=False, populate_from='title'),
        ),
    ]
