# Generated by Django 2.2.15 on 2021-04-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20210413_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
