# Generated by Django 2.2.15 on 2021-04-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_order_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Company_Name',
            field=models.CharField(max_length=250),
        ),
    ]
