# Generated by Django 2.2.15 on 2021-04-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_auto_20210418_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
