# Generated by Django 2.2.15 on 2021-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20210421_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='convention_image',
            field=models.ImageField(blank=True, null=True, upload_to='Hotel'),
        ),
    ]
