# Generated by Django 2.2.15 on 2021-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_auto_20210430_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CVC',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Card_Number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Expires',
            field=models.CharField(max_length=6),
        ),
    ]
