# Generated by Django 2.2.15 on 2021-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_auto_20210521_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Card_Number',
            field=models.CharField(max_length=16),
        ),
    ]
