# Generated by Django 2.2.15 on 2021-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_auto_20210526_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='duration_guest_NO_1_R1',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
