# Generated by Django 2.2.15 on 2021-05-26 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_auto_20210526_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_id'),
        ),
    ]
