# Generated by Django 2.2.15 on 2021-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_auto_20210528_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Number_OF_Guests',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], default=1, max_length=10),
        ),
    ]
