# Generated by Django 3.1 on 2020-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='title',
            field=models.CharField(blank=True, choices=[('M', 'Mr.'), ('R', 'Mrs.'), ('I', 'Miss.')], max_length=1, null=True),
        ),
    ]
