# Generated by Django 3.1 on 2020-09-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_details_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='convention_image',
            field=models.ImageField(default='Hotel/moha.jpeg', upload_to='Hotel'),
        ),
    ]
