# Generated by Django 3.1 on 2020-09-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200904_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='convention_image',
            field=models.ImageField(upload_to='Hotel'),
        ),
    ]
