# Generated by Django 3.1 on 2020-10-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_blog_weblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='weblog',
        ),
    ]
