# Generated by Django 2.2.15 on 2020-10-19 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20201015_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_id'),
        ),
    ]
