# Generated by Django 2.2.15 on 2020-10-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20201019_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Item'),
        ),
    ]
