# Generated by Django 2.2.15 on 2021-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20210316_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='random input', max_length=500),
        ),
    ]
