# Generated by Django 2.2.15 on 2021-03-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20210316_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
