# Generated by Django 2.2.15 on 2021-03-17 22:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20210316_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title'),
        ),
    ]
