# Generated by Django 2.2.15 on 2021-04-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20210413_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Hotel_Name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='Hotel_Rate',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
