# Generated by Django 2.2.15 on 2021-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_auto_20210418_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='convention_image',
            field=models.ImageField(blank=True, default='Hotel/moha.jpeg', null=True, upload_to='Hotel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='Hotel/moha.jpeg', null=True, upload_to='Hotel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
