# Generated by Django 2.2.15 on 2021-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='Haha', help_text='random #input', max_length=500),
        ),
    ]
