# Generated by Django 2.2.15 on 2021-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_auto_20210429_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='item',
            name='convention_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
